version: '3.8'
services: 
    main:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 8000:8000 
    queue:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'php artisan queue:work'
        depends_on: 
            - db         
    db:
        image: mysql:8.0
        environment: 
            MYSQL_DATABASE: main
            MYSQL_USER: admin
            MYSQL_ROOT: admin
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3306:3306